# Generated by Django 3.1.7 on 2021-03-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210331_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_product',
            field=models.BooleanField(default=False),
        ),
    ]
