# Generated by Django 3.1.7 on 2021-03-31 11:21

import core.models
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_productcontent_info_page_metrics_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontent',
            name='info_page_metrics_2',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=core.models.get_default_list, size=None),
        ),
    ]
