# Generated by Django 3.1.7 on 2021-03-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210331_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
