# Generated by Django 3.1.7 on 2021-04-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_category_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productcontent',
            name='landing_page_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
