# Generated by Django 3.1.7 on 2021-04-09 04:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_productimage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('blog_title', models.CharField(max_length=255, unique=True)),
                ('blog_image', models.FileField(blank=True, null=True, upload_to='')),
                ('blog_description', models.TextField()),
                ('blog_content', models.TextField()),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
