# Generated by Django 3.1.7 on 2021-04-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210412_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='bg_image',
        ),
        migrations.AddField(
            model_name='category',
            name='landing_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
