# Generated by Django 3.1.7 on 2021-04-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210416_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_product',
        ),
    ]
